"use client";

import { useState } from "react";
import { ChevronUp, Database } from "lucide-react";
import { cn } from "@/lib/utils";

interface SqlRevealProps {
  queries: string[];
}

/**
 * Collapsible reveal block that shows the SQL queries generated by the agent.
 * Intended for enterprise users familiar with SQL who want transparency into
 * the exact queries being executed against the data warehouse.
 */
export function SqlReveal({ queries }: SqlRevealProps) {
  const [isOpen, setIsOpen] = useState(false);

  if (!queries || queries.length === 0) return null;

  return (
    <div className="space-y-0">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-2 py-1.5 text-sm text-text-muted hover:text-text transition-colors"
      >
        <Database size={15} className="text-accent/70" />
        <span className="font-medium">
          {queries.length === 1 ? "View SQL query" : `View SQL queries (${queries.length})`}
        </span>
        <ChevronUp
          size={14}
          className={cn(
            "transition-transform duration-200",
            !isOpen && "rotate-180"
          )}
        />
      </button>

      {isOpen && (
        <div className="border-l-2 border-accent/20 pl-4 ml-2 animate-fade-in space-y-3 pb-2">
          {queries.map((sql, idx) => (
            <div key={idx}>
              {queries.length > 1 && (
                <p className="text-[11px] font-medium text-text-muted/60 uppercase tracking-wider mb-1">
                  Query {idx + 1}
                </p>
              )}
              <pre className="bg-[#1a1a2e] border border-border/50 rounded-lg p-3.5 overflow-x-auto text-[12px] leading-relaxed">
                <code className="font-mono text-[#c8d6e5] whitespace-pre-wrap break-words">
                  {formatSql(sql)}
                </code>
              </pre>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

/**
 * Lightweight SQL formatter — adds line breaks at major clause keywords
 * for readability without pulling in a full SQL parser.
 */
function formatSql(sql: string): string {
  // Normalize whitespace first
  let formatted = sql.replace(/\s+/g, " ").trim();

  // Add line breaks before major SQL keywords (only if not inside quotes)
  const keywords = [
    "SELECT", "FROM", "WHERE", "JOIN", "LEFT JOIN", "RIGHT JOIN",
    "INNER JOIN", "OUTER JOIN", "CROSS JOIN", "GROUP BY", "ORDER BY",
    "HAVING", "LIMIT", "OFFSET", "UNION", "UNION ALL", "AND", "OR",
  ];

  for (const kw of keywords) {
    // Match keyword preceded by space (not at start), case insensitive
    const regex = new RegExp(`(?<=\\s)(${kw})\\b`, "gi");
    formatted = formatted.replace(regex, `\n  $1`);
  }

  // Ensure SELECT is at the start (no leading newline)
  formatted = formatted.replace(/^\s*\n\s*/, "");

  return formatted;
}
