"""
Unit tests for agents/rm-prep/src/brief.py — RMBrief model and render_brief().

No external dependencies — pure Python / Pydantic.
"""
import sys
from pathlib import Path

import pytest

# Make the rm-prep src package importable without a full container install
sys.path.insert(0, str(Path(__file__).parents[2] / "agents" / "rm-prep" / "src"))

from brief import RMBrief, render_brief  # noqa: E402

pytestmark = pytest.mark.unit

# ── Fixtures ───────────────────────────────────────────────────────────────────

def _full_brief(**overrides) -> RMBrief:
    defaults = dict(
        client_name="Microsoft Corp.",
        meeting_date="2026-03-20",
        executive_summary=(
            "Microsoft is a strategic client with growing payment volumes. "
            "The relationship is healthy with 3 open opportunities totaling $2.5M."
        ),
        recent_activity=(
            "[CRM] Last interaction: Discovery meeting on Feb 25, 2026 with Jane Smith (CFO). "
            "Open task: Send Q1 proposal by March 31."
        ),
        payment_activity=(
            "[Payments] Total outbound: $45.2M over 360 days (+12% vs prior period). "
            "Primary rail: Wire (80%), ACH (20%). Trend: INCREASING."
        ),
        latest_news=(
            "[News] Reuters (Mar 10): Microsoft announced Azure expansion in Southeast Asia. "
            "Business implication: potential FX and cross-border payment growth."
        ),
        talking_points=[
            "Highlight Wire processing efficiency gains from Q4 migration",
            "Discuss FX hedging options given increased Asia-Pacific volume",
            "Present Q1 liquidity management proposal",
        ],
        suggested_questions=[
            "How is the Azure expansion affecting your treasury requirements?",
            "Are you satisfied with the current FX execution for SGD/USD flows?",
            "What is your target payment settlement timeline for APAC suppliers?",
        ],
        watch_items=(
            "⚠️ Three invoices >$1M pending settlement — follow up before meeting. "
            "✅ Payment volume trending up 12% — positive engagement signal."
        ),
        sources=[
            "[CRM: meeting Feb-25]",
            "[Payments: +12% vol QoQ]",
            "[News: Reuters Mar-10]",
        ],
    )
    defaults.update(overrides)
    return RMBrief(**defaults)


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 1: Model validation
# ─────────────────────────────────────────────────────────────────────────────

class TestRMBriefModel:
    def test_full_brief_is_valid(self):
        brief = _full_brief()
        assert brief.client_name == "Microsoft Corp."

    def test_meeting_date_optional(self):
        brief = _full_brief(meeting_date=None)
        assert brief.meeting_date is None

    def test_talking_points_is_list(self):
        brief = _full_brief()
        assert isinstance(brief.talking_points, list)
        assert len(brief.talking_points) >= 1

    def test_suggested_questions_is_list(self):
        brief = _full_brief()
        assert isinstance(brief.suggested_questions, list)

    def test_sources_is_list(self):
        brief = _full_brief()
        assert isinstance(brief.sources, list)


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 2: render_brief() markdown structure
# ─────────────────────────────────────────────────────────────────────────────

class TestRenderBrief:
    def setup_method(self):
        self.brief = _full_brief()
        self.md = render_brief(self.brief)

    def test_returns_string(self):
        assert isinstance(self.md, str)
        assert len(self.md) > 100

    def test_contains_h1_title(self):
        assert "# RM Meeting Preparation Brief" in self.md

    def test_contains_client_name(self):
        assert self.brief.client_name in self.md

    def test_contains_meeting_date(self):
        assert self.brief.meeting_date in self.md

    def test_all_seven_sections_present(self):
        for section in [
            "## 1. Executive Summary",
            "## 2. Recent Relationship Activity",
            "## 3. Payment Activity",
            "## 4. Latest News",
            "## 5. Suggested Talking Points",
            "## 6. Suggested Questions",
            "## 7. Watch Items",
        ]:
            assert section in self.md, f"Missing section: {section}"

    def test_talking_points_rendered(self):
        for tp in self.brief.talking_points:
            assert tp in self.md

    def test_suggested_questions_rendered(self):
        for q in self.brief.suggested_questions:
            assert q in self.md

    def test_sources_joined_with_pipe(self):
        # Sources should be joined as "src1 | src2 | src3"
        assert "[CRM: meeting Feb-25] | [Payments: +12% vol QoQ]" in self.md

    def test_disclaimer_present(self):
        assert "generated by AI" in self.md.lower() or "Verify key figures" in self.md

    def test_prepared_by_default(self):
        md = render_brief(self.brief)
        assert "RM Prep Agent" in md

    def test_prepared_by_custom(self):
        md = render_brief(self.brief, prepared_by="Alice Manager (test)")
        assert "Alice Manager (test)" in md

    def test_no_meeting_date_shows_upcoming(self):
        brief = _full_brief(meeting_date=None)
        md = render_brief(brief)
        assert "Upcoming" in md

    def test_empty_sources_fallback(self):
        brief = _full_brief(sources=[])
        md = render_brief(brief)
        # Should fall back to "CRM · Payments · News" or similar
        assert "CRM" in md and "Payments" in md

    def test_executive_summary_in_output(self):
        assert "strategic client" in self.md  # from fixture text

    def test_payment_activity_in_output(self):
        assert "[Payments]" in self.md

    def test_crm_activity_in_output(self):
        assert "[CRM]" in self.md
