"""
RM Prep Agent — brief data model and renderer.

RMBrief is the structured output of the synthesis node.
render_brief() converts it to formatted markdown for display.
"""
from typing import Optional
from pydantic import BaseModel, Field


class RMBrief(BaseModel):
    """Structured RM Meeting Preparation Brief."""
    client_name: str = Field(description="Name of the client company")
    meeting_date: Optional[str] = Field(None, description="Meeting date if known")
    executive_summary: str = Field(
        description="2-3 sentence summary of the most important things the RM needs to know before the meeting"
    )
    recent_activity: str = Field(
        description="Summary of recent CRM relationship history: last interaction, key contacts, open tasks. Cite dates and names from CRM data. Label as [CRM]."
    )
    payment_activity: str = Field(
        description="90-day payment analysis: total volumes, trend %, payment types, international corridors, new corridors. Label as [Payments]."
    )
    latest_news: str = Field(
        description="Recent news headlines with business implications. If no news, state 'No significant recent news detected.' Label as [News]."
    )
    talking_points: list[str] = Field(
        description="3-5 specific, actionable talking points grounded in the data — not generic advice"
    )
    suggested_questions: list[str] = Field(
        description="3-4 open-ended questions to ask the client during the meeting"
    )
    watch_items: str = Field(
        description="Risks, opportunities, or items requiring attention. Include both positive signals and warning signs."
    )
    sources: list[str] = Field(
        description="Short citations for key facts, e.g. '[CRM: last meeting Feb 25]', '[Payments: +15% volume Q-o-Q]', '[News: Reuters Mar 12]'"
    )


def render_brief(brief: RMBrief, prepared_by: str = "RM Prep Agent") -> str:
    """Render RMBrief as formatted markdown."""
    from datetime import datetime
    now = datetime.now().strftime("%B %d, %Y at %H:%M")
    talking = "\n".join(f"- {tp}" for tp in brief.talking_points)
    questions = "\n".join(f"- {q}" for q in brief.suggested_questions)
    sources = " | ".join(brief.sources) if brief.sources else "CRM · Payments · News"

    return f"""# RM Meeting Preparation Brief

**Client**: {brief.client_name}
**Meeting**: {brief.meeting_date or 'Upcoming'}
**Prepared**: {now} by {prepared_by}

---

## 1. Executive Summary

{brief.executive_summary}

---

## 2. Recent Relationship Activity

{brief.recent_activity}

---

## 3. Payment Activity

{brief.payment_activity}

---

## 4. Latest News

{brief.latest_news}

---

## 5. Suggested Talking Points

{talking}

---

## 6. Suggested Questions

{questions}

---

## 7. Watch Items

{brief.watch_items}

---

*Sources: {sources}*
*This brief was generated by AI. Verify key figures before the meeting.*
"""
